"""Type stubs for marlin.envelope — raw NMEA sentence parsing."""

from __future__ import annotations

from types import TracebackType
from typing import Literal, final

from .. import MarlinError

class EnvelopeError(MarlinError):
    variant: str

@final
class RawSentence:
    @property
    def start_delimiter(self) -> bytes: ...
    @property
    def talker(self) -> bytes | None: ...
    @property
    def sentence_type(self) -> str: ...
    @property
    def fields(self) -> tuple[bytes, ...]: ...
    @property
    def tag_block(self) -> bytes | None: ...
    @property
    def checksum_ok(self) -> bool: ...
    @property
    def raw(self) -> bytes: ...
    def as_dict(self) -> dict[str, object]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

class _EnvelopeIterator:
    def __iter__(self) -> _EnvelopeIterator: ...
    def __next__(self) -> RawSentence: ...

@final
class OneShotParser:
    def __new__(cls) -> OneShotParser: ...
    def feed(self, data: bytes) -> None: ...
    def next_sentence(self) -> RawSentence | None: ...
    def __iter__(self) -> _EnvelopeIterator: ...
    def iter(self, strict: bool = ...) -> _EnvelopeIterator: ...
    def __enter__(self) -> OneShotParser: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> Literal[False]: ...

@final
class StreamingParser:
    def __new__(cls, max_size: int = ...) -> StreamingParser: ...
    def feed(self, data: bytes) -> None: ...
    def next_sentence(self) -> RawSentence | None: ...
    def __iter__(self) -> _EnvelopeIterator: ...
    def iter(self, strict: bool = ...) -> _EnvelopeIterator: ...
    def __enter__(self) -> StreamingParser: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> Literal[False]: ...

def parse(data: bytes) -> RawSentence: ...

__all__ = [
    "EnvelopeError",
    "RawSentence",
    "OneShotParser",
    "StreamingParser",
    "parse",
]
