"""Type stubs for marlin.klv — MISB ST 0601 (UAS Datalink Local Set) KLV."""

from __future__ import annotations

from .. import MarlinError

class KlvError(MarlinError): ...

class St0601:
    def __init__(
        self,
        timestamp_us: int = ...,
        version: int | None = ...,
    ) -> None: ...
    # Framing / mandatory fields.
    timestamp_us: int
    version: int | None
    # Raw wire-integer escape hatches (read/write).
    raw_platform_heading: int | None
    raw_platform_pitch: int | None
    raw_platform_roll: int | None
    raw_platform_true_airspeed: int | None
    raw_sensor_latitude: int | None
    raw_sensor_longitude: int | None
    raw_sensor_true_altitude: int | None
    raw_sensor_horizontal_fov: int | None
    raw_sensor_vertical_fov: int | None
    raw_sensor_relative_azimuth: int | None
    raw_sensor_relative_elevation: int | None
    raw_sensor_relative_roll: int | None
    raw_slant_range: int | None
    raw_target_width: int | None
    raw_frame_center_latitude: int | None
    raw_frame_center_longitude: int | None
    raw_frame_center_elevation: int | None
    raw_target_location_latitude: int | None
    raw_target_location_longitude: int | None
    raw_target_location_elevation: int | None
    # Engineering-unit accessors: getter returns None on the wire sentinel;
    # setter clamps into the tag's valid range (never None).
    @property
    def platform_heading_degrees(self) -> float | None: ...
    @platform_heading_degrees.setter
    def platform_heading_degrees(self, value: float) -> None: ...
    @property
    def platform_pitch_degrees(self) -> float | None: ...
    @platform_pitch_degrees.setter
    def platform_pitch_degrees(self, value: float) -> None: ...
    @property
    def platform_roll_degrees(self) -> float | None: ...
    @platform_roll_degrees.setter
    def platform_roll_degrees(self, value: float) -> None: ...
    @property
    def platform_true_airspeed_mps(self) -> float | None: ...
    @platform_true_airspeed_mps.setter
    def platform_true_airspeed_mps(self, value: float) -> None: ...
    @property
    def sensor_latitude_degrees(self) -> float | None: ...
    @sensor_latitude_degrees.setter
    def sensor_latitude_degrees(self, value: float) -> None: ...
    @property
    def sensor_longitude_degrees(self) -> float | None: ...
    @sensor_longitude_degrees.setter
    def sensor_longitude_degrees(self, value: float) -> None: ...
    @property
    def sensor_true_altitude_meters(self) -> float | None: ...
    @sensor_true_altitude_meters.setter
    def sensor_true_altitude_meters(self, value: float) -> None: ...
    @property
    def sensor_horizontal_fov_degrees(self) -> float | None: ...
    @sensor_horizontal_fov_degrees.setter
    def sensor_horizontal_fov_degrees(self, value: float) -> None: ...
    @property
    def sensor_vertical_fov_degrees(self) -> float | None: ...
    @sensor_vertical_fov_degrees.setter
    def sensor_vertical_fov_degrees(self, value: float) -> None: ...
    @property
    def sensor_relative_azimuth_degrees(self) -> float | None: ...
    @sensor_relative_azimuth_degrees.setter
    def sensor_relative_azimuth_degrees(self, value: float) -> None: ...
    @property
    def sensor_relative_elevation_degrees(self) -> float | None: ...
    @sensor_relative_elevation_degrees.setter
    def sensor_relative_elevation_degrees(self, value: float) -> None: ...
    @property
    def sensor_relative_roll_degrees(self) -> float | None: ...
    @sensor_relative_roll_degrees.setter
    def sensor_relative_roll_degrees(self, value: float) -> None: ...
    @property
    def slant_range_meters(self) -> float | None: ...
    @slant_range_meters.setter
    def slant_range_meters(self, value: float) -> None: ...
    @property
    def target_width_meters(self) -> float | None: ...
    @target_width_meters.setter
    def target_width_meters(self, value: float) -> None: ...
    @property
    def frame_center_latitude_degrees(self) -> float | None: ...
    @frame_center_latitude_degrees.setter
    def frame_center_latitude_degrees(self, value: float) -> None: ...
    @property
    def frame_center_longitude_degrees(self) -> float | None: ...
    @frame_center_longitude_degrees.setter
    def frame_center_longitude_degrees(self, value: float) -> None: ...
    @property
    def frame_center_elevation_meters(self) -> float | None: ...
    @frame_center_elevation_meters.setter
    def frame_center_elevation_meters(self, value: float) -> None: ...
    @property
    def target_location_latitude_degrees(self) -> float | None: ...
    @target_location_latitude_degrees.setter
    def target_location_latitude_degrees(self, value: float) -> None: ...
    @property
    def target_location_longitude_degrees(self) -> float | None: ...
    @target_location_longitude_degrees.setter
    def target_location_longitude_degrees(self, value: float) -> None: ...
    @property
    def target_location_elevation_meters(self) -> float | None: ...
    @target_location_elevation_meters.setter
    def target_location_elevation_meters(self, value: float) -> None: ...
    # Unrecognized tags, preserved verbatim as (tag, bytes) in wire order.
    @property
    def unknown(self) -> list[tuple[int, bytes]]: ...

class TagInfo:
    """Read-only metadata for one typed ST 0601 tag: wire number, field base
    name (e.g. ``sensor_latitude``), and engineering unit (``None`` if none)."""

    number: int
    name: str
    unit: str | None

# The 16-byte UAS Datalink Local Set Universal Label every ST 0601 packet is framed with.
UAS_LS_KEY: bytes

def decode(data: bytes) -> St0601: ...
def encode(set: St0601) -> bytes: ...
def precision_timestamp(data: bytes) -> int | None: ...
def tags() -> list[TagInfo]: ...
def tag_number(name: str) -> int | None: ...
def tag_name(number: int) -> str | None: ...

__all__ = [
    "UAS_LS_KEY",
    "KlvError",
    "St0601",
    "TagInfo",
    "decode",
    "encode",
    "precision_timestamp",
    "tag_name",
    "tag_number",
    "tags",
]
